### PR TITLE
Fix cpu demo crash on aarch64 platform

### LINKED ISSUE #244: [bug][AArch64] cpu demo crash
We encounter following error on AArch64 platform when running cpu demo.
```
*** stack smashing detected ***: terminated
``` 

call stack:
image

### PR DESCRIPTION
**Pull request by wyzero**
We try to fix #244 in this PR. The root cause of the crash is still not clear. After doing some experiments, we think that it isn't likely to be the bug of BladeDISC itself.
- The crash could be re-produced on a graph with a single GEMM op using BladeDISC TF bridge.
- Same GEMM op test is ok if we do the test in UT environments (not using TF bridge) or use BladeDISC torch bridge.
-  Codegen kernel runs successfully using BladeDISC TF bridge.
-  if we use the wheel file from ARM community instead of `pip install tensorflow-aarch64`, GEMM op test is ok using BladeDISC TF bridge.

Thus, we provide a workaround to fix #244 by replacing the wheel package.

### CODE REVIEW

**Comment by wyzero** [comment]
to #227

**Review by linearhit — APPROVED** [review]
LGTM

File: tao_compiler/mlir/xla/ral/context/mkldnn/ideep/ideep/operators/matmul.hpp [hunk 1]
```diff
@@ -53,10 +53,10 @@ struct matmul_forward : public dnnl::matmul,
       data_type x_dtype = data_type::f32,
       const engine& aengine = engine::cpu_engine()) {
     auto ndims = weights_dims.size();
-    auto x_dims = weights_dims;
+    dims x_dims = weights_dims;
```
Comment (Yancey1989) [inline tao_compiler/mlir/xla/ral/context/mkldnn/ideep/ideep/operators/matmul.hpp:56]: just curious, why can not use `auto` ?

Comment (wyzero) [reply tao_compiler/mlir/xla/ral/context/mkldnn/ideep/ideep/operators/matmul.hpp:56]: Two reasons：
- using `auto` in line 59 is a bug (auto-detected type is not dims)
- using `auto` in line 57 is ok, while we follow community best practice to avoid using auto as long as it will not increase two much typings.
